cdk-pipe:
  commands:
    cdk:
      bootstrap: npx cdk bootstrap
      deploy: npx cdk deploy
      synth: npx cdk synth
      diff: npx cdk diff
    npm:
      checks:
        lint: npm run lint
        format: npm run format
      install: npm ci
  beforeScripts:
    - npm version
  # afterScripts:
  #   - apk add tree
